services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.public
    ports:
      - '8001:8001'
      
  matching-service:
    build:
      context: ./matching-service
      dockerfile: Dockerfile.public
    ports:
      - '8002:8002'
      
  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile.public
    ports:
      - '8003:8003'
      
  frontend:
    build:
      context: ./peer-prep
      dockerfile: Dockerfile.public
    ports:
      - '5173:5173'
      
  redis:
    build:
      context: ./redis-server
      dockerfile: Dockerfile    
    ports:
      - "6379:6379"  # Expose Redis port to the host
