apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: peerprep
  name: peerprep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peerprep
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: peerprep
    spec:
      containers:
      - image: asdfghjklxd/peerprep-user-service:latest
        name: user-service
        ports:
        - containerPort: 8001
        resources:
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: USER_SERVICE_PORT
              name: peerprep-secrets
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: ACCESS_TOKEN_SECRET
              name: peerprep-secrets
        - name: MONGO_PROD_URI
          valueFrom:
            secretKeyRef:
              key: USER_SERVICE_MONGO_PROD_URI
              name: peerprep-secrets
      
      - image: asdfghjklxd/peerprep-question-service:latest
        name: question-service
        ports:
        - containerPort: 8003
        resources:
        env:
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: ACCESS_TOKEN_SECRET
              name: peerprep-secrets
        - name: DEV_URI
          valueFrom:
            secretKeyRef:
              key: QUESTION_SERVICE_DEV_URI
              name: peerprep-secrets

      - image: asdfghjklxd/peerprep-matching-service:latest
        name: matching-service
        ports:
        - containerPort: 8002
        resources:
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: MATCHING_SERVICE_PORT
              name: peerprep-secrets
        - name: MONGO_TEST_URI
          valueFrom:
            secretKeyRef:
              key: MATCHING_SERVICE_MONGO_TEST_URI
              name: peerprep-secrets

      - image: asdfghjklxd/peerprep-collaboration-service:latest
        name: collaboration-service
        ports:
          - containerPort: 8004
        resources:
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_HOST
              name: peerprep-secrets
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_PORT
              name: peerprep-secrets
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_REDIS_HOST
              name: peerprep-secrets
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_REDIS_PORT
              name: peerprep-secrets
