# https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/expressjs
# This is used to push images onto DockerHub
FROM node:20

# expose 8003 port for access to the container
EXPOSE 8003

# Set work dir to prevent retarts
WORKDIR /question-service

# copy all files into the Docker container
COPY . .

# install node libraries
RUN npm install

# execute the server
CMD ["node", "index.js"]