services:
  redis:
    container_name: redis
    image: 'redis:latest'
    restart: always
    command: redis-server --save 1 1 --loglevel warning
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

  collaboration-service:
    container_name: collaboration-service
    build:
      context: .
      dockerfile: Dockerfile.public
    ports:
      - '8004:8004'
    depends_on:
      - redis

volumes:
  redis:
    driver: local
